### ISSUE TITLE
Anon key is not assigned, cannot make anon requests

### ISSUE THREAD

**Issue by matthew-rimmer** [fenix-hub/godot-engine.supabase#11]
If you attempt to call a query without signing in, you end up with the error:

    empty >> JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1): empty (empty)`
    
And no data is returned.

Printing `_bearer` in the `query` function shows that the anon key is not assigned:

     Authorization: Bearer %s

And as such, I can't make anon requests. There is a workaround, by manually setting `_bearer` to the anon key:

    var string = ["Authorization: Bearer x.y.z"] # (x.y.z being the anon key)
    Supabase.auth._bearer = string
    
It can successfully query the database.

**Comment by fenix-hub** [comment]
Hi, thanks for opening this issue and finding a workaround.
Due to personal business it's hard for me to stay on track with recent Supabase updates.
I'll update the whole library as soon as I'll got time, including this.

**Comment by ShatReal** [comment]
...I don't think is fixed? I get the same issue. But the workaround still works.
