### ISSUE TITLE
mixed tabs indentation error

### ISSUE THREAD

**Issue by shafnaz** [fenix-hub/godot-engine.supabase#36]
@fenix-hub , there seems to be a simple error in the file, I just installed it from Godot.
auth.gd
![image](https://user-images.githubusercontent.com/37254287/140453420-99ec5104-3fa1-434a-ba48-b3828c93c0f1.png)

i just retabbed line above
Supabase version 3.1

**Comment by fenix-hub** [comment]
@shafnaz 
https://github.com/fenix-hub/godot-engine.supabase/tree/v3.2.0 has been released, you can download it directly from github. To get it from the AssetLib a couple of days should be waited
