### ISSUE TITLE
calling .eq.update crashes it? i'm sorry, I don't really know if i did something wrong

### ISSUE THREAD

**Issue by ShatReal** [fenix-hub/godot-engine.supabase#41]
So my code is 
```
	var query_task := Supabase.database.query(SupabaseQuery.new().from("creators").eq("id", "13").update({
		"data": {"key2": "value2"},
	}))
```
This should update it, right? Anyway, it crashes the game on the database_task _on_task_completed function. Apparently result_body is set to an array instead of a dictionary? I don't know how that's possible.

**Comment by ShatReal** [comment]
also, now all my queries are returning an empty dictionary. i have no clue what caused this, it was working fine earlier.

**Comment by ShatReal** [comment]
Also, I tried calling sign_in_anonymous() but i just got the error "invalid_request >> refresh token required"

**Comment by fenix-hub** [comment]
> So my code is
> 
> ```
> 	var query_task := Supabase.database.query(SupabaseQuery.new().from("creators").eq("id", "13").update({
> 		"data": {"key2": "value2"},
> 	}))
> ```
> 
> This should update it, right? Anyway, it crashes the game on the database_task _on_task_completed function. Apparently result_body is set to an array instead of a dictionary? I don't know how that's possible.

I can check that later, eventually the endpoint returns an Array if there are multiple rows updated instead of one. Maybe I'm mapping that wrongly

**Comment by fenix-hub** [comment]
> Also, I tried calling sign_in_anonymous() but i just got the error "invalid_request >> refresh token required"

I think that anonymous login is not supported anymore, or "fixed" since it used the anonymous key but without identifying any user (which is not secure anyway).
You can try this workaround https://github.com/supabase/gotrue/issues/68

**Comment by ShatReal** [comment]
okay, will do!

**Comment by ShatReal** [comment]
For the first issue, I didn't have permission to update the table since my policies were set incorrectly, so the returned array was empty. I have them set correctly now.

**Comment by ShatReal** [comment]
Now I can't upload images 😭 , the error is just empty

**Comment by ShatReal** [comment]
I am calling `Supabase.storage.from("public").upload("thumbnails/test.png", "user://icon.png")` and it doesn't work 😭

**Comment by fenix-hub** [comment]
@ShatReal the error could be empty because you didn't authenticate before uploading a file

**Comment by fenix-hub** [comment]
About the empty error: that's an issue coming from supabase backend, sadly :\
I'll reach out to Supabase devs to ask for a meaningful error
