### ISSUE TITLE
Issue trying to query the database, returns null

### ISSUE THREAD

**Issue by SeaKrill** [fenix-hub/godot-engine.supabase#42]
Been working on this for a while and cant figure out why its doing it. When I try to query the database it keeps giving me a null response.

`var query : DatabaseTask = get_node(str(player_id)).database.query(SupabaseQuery.new().from("profiles").select(["avatar","username","points"]).eq("id",user_id))`

is the part thats supposed to query.

Odd thing is it works in another project that i was using to test stuff. Nearly identical code.

`var query_profile : DatabaseTask = Supabase.database.query(SupabaseQuery.new().from("profiles").select(["avatar","username","points"]).eq("id",Supabase.user.id))`

also tried it using one of your example snippets:

```
func get_user(user_id : String) -> DatabaseTask:
	var user_query : SupabaseQuery = SupabaseQuery.new().from("profiles").select(["avatar","username","points"]).eq("id",user_id)
	return Supabase.database.query(user_query)
```

same result, null. Not sure why

**Comment by SeaKrill** [comment]
Strange, I found that if i print the _result in database_task.gd:
```
func complete(_result,  _error : SupabaseDatabaseError = null) -> void:
	data = _result
	error = _error
	if _handler : _handler.queue_free()
	emit_signal("completed", self)
```
it prints the data i want but for some reason it isnt being pushed to the actual query

**Comment by SeaKrill** [comment]
Figured it out:
`var query : DatabaseTask = yield(get_node(str(player_id)).database.query(SupabaseQuery.new().from("profiles").select(["avatar","username","points"]).eq("id",user_id)), "completed")`
Had to wait for the var to actually finishing getting the data. Yield function was added and that solved it.

**Comment by fenix-hub** [comment]
@SeaKrill glad you solved. 
Just to clerify the `Supabase.database.query(<query>)` is what actually executes your query and what returns the DatabaseTask, so you either yield on that function, or connect to a signal. DatabaseTask result is always available with `DatabaseTask.data` after execution.
In your case you can call `var profile := yield(get_user(id), "completed")`
