### ISSUE TITLE
Issue querying again

### ISSUE THREAD

**Issue by SeaKrill** [fenix-hub/godot-engine.supabase#43]
Sorry to be a nuisance but I'm having another issue with the query function.

Trying to be able to check if an email already exists in the database on account creation. So far i've already set it up so it puts the email into the public profile of the user but it keeps turning up null again when i try to check it against the query.

```
remote func try_sign_up(email):
	print(email)
	var player_id = get_tree().get_rpc_sender_id()
	var player = get_parent().get_node("Players/" + str(player_id))
	var _email = yield(check_user(player, email), "completed")
	print(_email.data)

func check_user(player, email) -> DatabaseTask:
	var query : SupabaseQuery = SupabaseQuery.new().from("profiles").select(["email"]).Is("email", email, true)
	return player.database.query(query)
```

the database so far is just setup with a "profiles" table with a column called email where the users email is placed on sign up.
am i setting up the query correctly?

I'm just trying to check, in profiles/email is there queried email. if yes print true, if not print false

**Comment by fenix-hub** [comment]
`.Is("email", email, true)`
the third parameter is a *negation* [check here](https://github.com/fenix-hub/godot-engine.supabase/blob/04c3759ff6e8718d81fc86d3abdec9bc14f195e8/addons/supabase/Database/query.gd#L226), which means that if set to `true` it will check the opposite (select the column 'email' for all the rows where `email` value is *DIFFERENT* from the player's email)

**Comment by SeaKrill** [comment]
Tried `.Is("email", email)` too but it still comes out as null.

**Comment by fenix-hub** [comment]
Can you print `_email.error` in console to know if there's any error?
As a best practice you could always check
```gdscript
if _email.error != null:
   # _email.data
else:
   # error
```

**Comment by SeaKrill** [comment]
`empty >> JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1):  (empty)`

**Comment by fenix-hub** [comment]
Did you authenticate before making database calls?

**Comment by SeaKrill** [comment]
How would I do that?

**Comment by SeaKrill** [comment]
If i understnad correctly the database call is being made on a node that has its own auth and database node

**Comment by fenix-hub** [comment]
> How would I do that?

Supabase.auth.sign_in()

**Comment by fenix-hub** [comment]
If you sign_up with an already existing email, a coherent erorr will be returned, so you can check that way.
Anyway database operation must be always authenticated with a JWT (so a logged user)

**Comment by SeaKrill** [comment]
I came up with this but when I try to create an account with an email that exists the error prints as null
```
remote func try_sign_up(email, password) -> SupabaseUser:
	var player_id = get_tree().get_rpc_sender_id()
	var player = get_parent().get_node("Players/" + str(player_id))
	var result: AuthTask = yield(player.auth.sign_up(email, password), "completed")
	print(result.error)
	return result
```

**Comment by SeaKrill** [comment]
When I print out the _error in auth task i do get `null` but then there is a second print that happens that pops up `invalid_request >> refresh_token required` if that has anything to do with it

**Comment by fenix-hub** [comment]
You can already call Database Function in this SDK through the /rpc API

**Comment by SeaKrill** [comment]
How would I go about writing this supabase function if you don't mind me asking?

**Comment by SeaKrill** [comment]
```
create function public.check_user() 
returns bool
arguments _email text
language plpgsql 
security invoker set search_path = public
as $$
begin
  select exists (select * from profiles where profiles.email = _email);
end;
$$;
```

**Comment by fenix-hub** [comment]
`empty >> JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1): (empty)`
could mean that you are making the request without the JWT, since authentication is required for the function. You could try removing authentication for the database function

**Comment by SeaKrill** [comment]
So I think i've got a work around but theres still some bugs.
I now sign the person in as anonymous when they try to create an account to access the database for the check but I now get this error. Which makes me feel like either my postgres isnt right or my rpc call
`42601 >> query has no destination for result data: Null (If you want to discard the results of a SELECT, use PERFORM instead.)`

**Comment by fenix-hub** [comment]
`42601 >> query has no destination for result data: Null (If you want to discard the results of a SELECT, use PERFORM instead.)`
You are making a `select exists` query but don't store neither return the result in your function. Also, you don't actually need the select statement since the [EXISTS](https://www.postgresql.org/docs/current/functions-subquery.html) operator already returns true/false.
You could write your function as 
```sql
create function public.check_user(email text) 
returns bool
language plpgsql 
security invoker set search_path = public
as $$
begin
  return exists (select * from profiles where profiles.email = check_user.email);
end;
$$;
```

**Comment by SeaKrill** [comment]
Got it working with
```
create function public.check_user(check_email text) 
returns text
language plpgsql 
security invoker set search_path = public
as $$
begin
  return exists (select * from profiles where profiles.email = check_email);
end;
$$;
```

otherwise you get an error in godot
```
SCRIPT ERROR: Invalid call. Nonexistent function 'empty' in base 'bool'.
          at: SupabaseDatabase._on_task_completed (res://Scripts/Database/database.gdc:63)
```
so changing bool to text prevents it. It still works as bool, it just pops an error in the debug.

Otherwise this works now!
Thanks so much for taking so much time to help me out, I really appreciate it!

**Comment by fenix-hub** [comment]
Happy to know I could help you. 
Have a nice day!
